version: "3"
services:
  mysql_compose:
    image: mysql:5.7
    container_name: mysql_compose
    ports:
      - 3306:3306
    volumes:
      - /home/user/mysql/data:/var/lib/mysql
      - /home/user/mysql/conf/mymysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      # MYSQL_ROOT_PASSWORD: "123456"
