version: '2'
services:
  master:
    image: redis      
    container_name: redis-master
    command: redis-server --requirepass 123456
    ports:
    - "6379:6379"
    networks:
    - sentinel-master
    volumes:
    - /Users/yu/Percy/redis/master/data:/data 
  slave1:
    image: redis                
    container_name: redis-slave-1
    ports:
    - "6380:6379"           
    command: redis-server --slaveof redis-master 6379 --requirepass 123456 --masterauth 123456 
    depends_on:
    - master
    networks:
    - sentinel-master
    volumes:
    - /Users/yu/Percy/redis/slave1/data:/data
  slave2:
    image: redis                
    container_name: redis-slave-2
    ports:
    - "6381:6379"
    command: redis-server --slaveof redis-master 6379 --requirepass 123456 --masterauth 123456
    depends_on:
    - master
    networks:
    - sentinel-master
    volumes:
    - /Users/yu/Percy/redis/slave1/data:/data
networks:
  sentinel-master:
