version: '2'
services:
  sentinel1:
    image: redis
    container_name: redis-sentinel-1
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
    - "26379:26379" 
    volumes:
    - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    - /Users/yu/Percy/redis/sentinel1/sentinel_log:/usr/local/etc/redis/sentinel_log
  sentinel2:
    image: redis
    container_name: redis-sentinel-2
    ports:
    - "26380:26379"           
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
    - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    - /Users/yu/Percy/redis/sentinel2/sentinel_log:/usr/local/etc/redis/sentinel_log
  sentinel3:
    image: redis
    container_name: redis-sentinel-3
    ports:
    - "26381:26379"           
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
    - ./sentinel3.conf:/usr/local/etc/redis/sentinel.conf
    - /Users/yu/Percy/redis/sentinel3/sentinel_log:/usr/local/etc/redis/sentinel_log
networks:
  default:
    external:
      name: compose_sentinel-master
